runtime: python39

entrypoint: gunicorn -b :$PORT otter_backend_impl.wsgi  # 确保替换为你的项目名称

env_variables:
  DJANGO_SETTINGS_MODULE: "otter_backend_impl.settings"  # 确保替换为你的项目名称

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto