runtime: python39
service: default

entrypoint: gunicorn -b :$PORT django_project.wsgi  # 确保替换为你的项目名称
instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "django_project.settings"  # 确保替换为你的项目名称
  HF_TOKEN: "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"

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto